version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - aws --version
      - echo "ECR_REPO_URL = $ECR_REPO_URL"
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin $ECR_REPO_URL

  pre_build:
    commands:
      - echo Test started on `date`
      - echo "skipping test"
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew clean build -x test
      - docker build -t $ECR_REPO_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker push $ECR_REPO_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION


  post_build:
    commands:
      - echo "Running post build commands"
artifacts:
  files:
    - build/libs/quiz-0.0.1-SNAPSHOT.jar
