version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - aws --version
      - echo "ECR_URL = $ECR_URL"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URL

  pre_build:
    commands:
      - echo Test started on `date`
      - echo "skipping test"
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew clean build
      - echo "ECR_URL = $ECR_URL , ECR_REPO_NAME=$ECR_REPO_NAME , CODEBUILD_RESOLVED_SOURCE_VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - echo "$ECR_URL/$ECR_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - docker build -t "$ECR_URL/$ECR_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION" .
      - docker push "$ECR_URL/$ECR_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION"


  post_build:
    commands:
      - echo "Running post build commands"
artifacts:
  files:
    - build/libs/quiz-0.0.1-SNAPSHOT.jar

reports:
  test-coverage:
    files:
      -  '**/*.xml'
    base-directory: 'build/jacoco/test'
    file-format: 'JACOCOXML'
  test-result:
    files:
      -  '**/TEST-*.xml'
    base-directory: 'build/test-results/test'
    file-format: 'JUNITXML'