server:
  port: 8081
management:
  endpoints:
    web:
      path-mapping:
        health: /
      base-path: /
  endpoint:
    health:
      enabled: true

spring:
  jackson:
    default-property-inclusion: non_null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-southeast-1.amazonaws.com/${POOL_ID}
  flyway:
    enabled: true
    baselineVersion: 0.0.0.0
    schemas: public
    baseline-on-migrate: true
    placeholder-replacement: false
    locations: classpath:db/migration
    outOfOrder: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  datasource:
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    hikari:
      maximum-pool-size: 10
      schema: public

logging:
  level:
    com:
      toptalproject:
        quiz: ${LOGGING_LEVEL:DEBUG}
    org:
      springframework:
        security: ${LOGGING_LEVEL:INFO}

app:
  defaultClient: ${WEB_CLIENT_ID}
  clientConfigs:
    - clientId: ${WEB_CLIENT_ID}
      redirectUri: ${WEB_REDIRECT_URI}


