server:
  port: ${SERVER_PORT:8080}

spring:
  jackson:
    default-property-inclusion: non_null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-southeast-2.amazonaws.com/${POOL_ID}
  flyway:
    enabled: true
    baselineVersion: 0.0.0.0
    schemas: public
    baseline-on-migrate: true
    placeholder-replacement: false
    locations: classpath:db/migration
    outOfOrder: true
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    hikari:
      schema: public

logging:
  level:
    com:
      toptalproject:
        quiz:
          '*': ${LOGGING_LEVEL:DEBUG}
    org:
      springframework:
        security: ${LOGGING_LEVEL:INFO}

app:
  clientConfigs:
    - clientId: ${WEB_CLIENT_ID:3e074qfjrs0ba81g4p8tthhk5u}
      redirectUri: ${WEB_REDIRECT_URI:http://localhost:8080/welcome}


